namespace GameEngine.Core.Nodes;

// before we directly compared the actual strings which means this is not being detected: [GameEngine.AutoGenerator.GenerateComponentInterface]
// now we directly look if the attribute string contains the name
//todo: even this would work because we check for the actual string containing the name: [Something.Blablabla.GenerateComponentInterface.Blabla]

public partial class ExampleComponent : Node, ITransform {
    
    // Awake Callback
    protected override void OnAwake() {
        base.OnAwake();
    }
    
    // Update Callback
    protected override void OnUpdate() {
        base.OnUpdate();
    }
    
    //autogenerated
//    public ExampleComponent(Node? parentNode = null) : base(parentNode) {
//        ChildNodes.Add(new GameEngine.Core.Nodes.Transform());
//        // ...
//    }
    
}
